In [1]:
import cv2
import os
import numpy as np

In [2]:
anime_cascade = cv2.CascadeClassifier('animeface/lbpcascade_animeface.xml')

In [3]:
files = os.listdir(r'C:\Users\haho6\Desktop\Datas\All')

In [4]:
def crop(arr,x,y,r):
    
    res = []
    for i in arr[y:y+r]:
        res.append(i[x:x+r])
    return np.array(res)

In [6]:
c = 356
for file in files:
    c+=1
    img = cv2.imread(r'Datas\\All\\' + file)
    gray = cv2.imread(r'Datas\\All\\' + file,0)
    if gray is None:
        break
    if img is None:
        break
    cv2.imshow('img', gray)
    faces = anime_cascade.detectMultiScale(gray)
    for (x, y, w, h) in faces:
        if x and y and w and w > 50:
            re_img = crop(img, x, y, w)

    cv2.imwrite(r"Datas\\result\\face\\{}.jpg".format(c), re_img)
    cv2.destroyAllWindows()

[[134 101 211 211]]
[[149  43 115 115]]
[[182 175 108 108]]
[[222  99 174 174]]
[[191 107 173 173]]
[[243  95 118 118]]
[[281  83 181 181]]
[[205 236 353 353]
 [ 47  81 659 659]]
[[235  51 131 131]]
[[352 186 174 174]]
()
[[219 125 279 279]]
[[283  79 175 175]]
[[281  93 238 238]]
[[172 128 278 278]]
[[843  91 102 102]
 [270  98  96  96]]
[[233 161 134 134]]
[[273 312 196 196]]
[[270 187 364 364]]
[[340 196 246 246]]
[[328  87 197 197]]
[[177  73 148 148]]
[[536 280 180 180]]
[[537 110 184 184]]
[[201  57  93  93]]
[[255  78  91  91]
 [701  81  92  92]]
[[592  98 197 197]]
[[282 118 258 258]]
()
[[435 101 140 140]
 [286 110 127 127]]
[[ 92  79 197 197]]
[[193 204 302 302]
 [314 803 109 109]]
[[145 100 233 233]]
[[378 416 159 159]]
[[266 124 142 142]]
[[307 142 180 180]]
[[611 194 242 242]
 [192 243 252 252]]
[[774 310 274 274]]
[[164 121 260 260]]
[[235  97 131 131]]
[[297 125 234 234]]
[[513 134 269 269]]
()
()
[[249 130 223 223]]
()
[[263 186 370 370]]
[[491 105 116 116]]
[[131 150 2

[[ 60 190 250 250]
 [205  88 267 267]]
[[311 118 121 121]
 [467  85 150 150]
 [334 138  72  72]]
[[523 119 155 155]]
()
[[506  90  84  84]]


AttributeError: 'NoneType' object has no attribute 'shape'